language: python
python:
  - '3.6'
env:
  - SECRET_KEY=secret
install:
  - pip install -r requirements.txt
  - pip install coverage pylint
services:
  - mysql
script:
  - coverage run --source . -m pytest -v
notifications:
  email: false
